In [1]:
import numpy as np

# question 1

In [25]:
arr = np.arange(1,13) .reshape(3, 4)
print(arr)
print(f"First row: {arr[0]}")
print(f"Second column: {arr[: , 1]}")
print(f"Sixth Element: {arr[1 , 1]}")
print(f"First Two Row: \n {arr[:2]}")
print(f"Last 2 column: \n {arr[:,-2:]}")
print(f"Reverse the array: \n {arr[::-1]}")




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Second column: [ 2  6 10]
Sixth Element: 6
First Two Row: 
 [[1 2 3 4]
 [5 6 7 8]]
Last 2 column: 
 [[ 3  4]
 [ 7  8]
 [11 12]]
Reverse the array: 
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


# Question 2 -- NumPy operations

In [30]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(f"The sum of two array is:{a + b}")
print(f"The diff of two array is:{a - b}")
print(f"The product of two array is:{a * b}")
print(f"The division of two array is:{a / b}")

print(a + 5)
print(a * 2)


The sum of two array is:[11 22 33 44]
The diff of two array is:[ 9 18 27 36]
The product of two array is:[ 10  40  90 160]
The division of two array is:[10. 10. 10. 10.]
[15 25 35 45]
[20 40 60 80]


# Question 3 NumPy Methods

In [41]:
a = np.array([10, 20, 30, 40, 50])

# LEVEL --- 1
print(f"The original array is: {a}")
print(f"The sum of all element is: {np.sum(a)}")
print(f"The mean of all element is: {np.mean(a)}")
print(f"The maximum value of the array is: {np.max(a)}")
print(f"The minimum value of the array is: {np.min(a)}")

# LEVEL --- 2
print(f"The index of the max value: {np.argmax(a)}")
print(f"The index of the min value: {np.argmin(a)}")

# LEVEL --- 3

marks = np.array([78,65,92,55,88,71])

print(f"\nThe marks students got : {marks}")
print(f"The total marks is : {np.sum(marks)}")
print(f"The average marks is : {np.mean(marks)}")
print(f"The highest marks is : {np.max(marks)}")
print(f"The lowest marks is : {np.min(marks)}")
print(f"the index of the student who got the highest marks : {np.argmax(marks)}")
print(f"the index of the student who got the lowest marks : {np.argmin(marks)}")
print(f"the standard deviation : {np.std(marks)}")





The original array is: [10 20 30 40 50]
The sum of all element is: 150
The mean of all element is: 30.0
The maximum value of the array is: 50
The minimum value of the array is: 10
The index of the max value: 4
The index of the min value: 0

The marks students got : [78 65 92 55 88 71]
The total marks is : 449
The average marks is : 74.83333333333333
The highest marks is : 92
The lowest marks is : 55
the index of the student who got the highest marks : 2
the index of the student who got the lowest marks : 3
the standard deviation : 12.798654443165328
