In [1]:
import numpy as np

# question 1

In [25]:
arr = np.arange(1,13) .reshape(3, 4)
print(arr)
print(f"First row: {arr[0]}")
print(f"Second column: {arr[: , 1]}")
print(f"Sixth Element: {arr[1 , 1]}")
print(f"First Two Row: \n {arr[:2]}")
print(f"Last 2 column: \n {arr[:,-2:]}")
print(f"Reverse the array: \n {arr[::-1]}")




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Second column: [ 2  6 10]
Sixth Element: 6
First Two Row: 
 [[1 2 3 4]
 [5 6 7 8]]
Last 2 column: 
 [[ 3  4]
 [ 7  8]
 [11 12]]
Reverse the array: 
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


# Question 2 -- NumPy operations

In [30]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(f"The sum of two array is:{a + b}")
print(f"The diff of two array is:{a - b}")
print(f"The product of two array is:{a * b}")
print(f"The division of two array is:{a / b}")

print(a + 5)
print(a * 2)


The sum of two array is:[11 22 33 44]
The diff of two array is:[ 9 18 27 36]
The product of two array is:[ 10  40  90 160]
The division of two array is:[10. 10. 10. 10.]
[15 25 35 45]
[20 40 60 80]
