## Numpy array and basics

In [3]:
import numpy as np

### Creating array from list

In [6]:
arr_1d = np.array([1,2,3,4,5])
print(f"1D array: {arr_1d}")

arr_2d = np.array([[1,2],[3,4]])
print(f"2D array: {arr_2d}")

1D array: [1 2 3 4 5]
2D array: [[1 2]
 [3 4]]


### List vs numpy array

In [5]:
py_list = [1,2,3]
print(f"List multiplication is: {py_list * 2}")

py_arr = np.array([1,2,3])
print(f"Array multiplication is: {py_arr * 2}")

List multiplication is: [1, 2, 3, 1, 2, 3]
Array multiplication is: [2 4 6]


### Creating Array from Scratch

In [ ]:
zeros = np.zeros((3,4))
print(f"Zeros array :\n {zeros}")

ones = np.ones((3,3))
print(f"ones array :\n {ones}")

full = np.full((3,3), 7)
print(f"full array :\n {full}")

random = np.random.random((2,2))
print(f"random array :\n {random}")

sequence = np.arange(0,11,2)
print(f"sequence array :\n {sequence}")


Zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array :
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random array :
 [[0.60003371 0.22004098]
 [0.65919579 0.72818083]]
sequence array :
 [0 2 4 6 8]
